### PR TITLE
Updated the README.md

### PR DESCRIPTION
**Pull request by shivkanwer**
Added missing cluster flag to the ```eksctl create``` command.

### CODE REVIEW

**Review by nimakaviani — APPROVED** [review]
LGTM

**Comment by nimakaviani** [comment]
Thanks for the change @shivkanwer, looks good.

this other request I had on issue #14 would also be good to go in with this same PR. can you please push another commit with the update to the eksctl version to this same PR?
> it seems like we should update the [requirements](https://github.com/cnoe-io/reference-implementation-aws?tab=readme-ov-file#requirements) section with information on eksctl and its version as well.

**Comment by shivkanwer** [comment]
I have added the eksctl and its version to the requirements section and made another commit. Please review.

**Comment by nimakaviani** [comment]
awesome, thank you!

**Pull request merged**
