### PR TITLE
Updating and Fixing EKS Cluster Config

### PR DESCRIPTION
**Pull request by elamaran11**
Updating and Fixing EKS Cluster Config.

### CODE REVIEW

**Comment by nimakaviani** [comment]
thanks @elamaran11 ... can you please sign the commit for the DCO. it should be as simple as doing a `git commit -s`

**Comment by elamaran11** [comment]
@nimakaviani I did add a new commit with `git commit -s -m "DCO` but it does not work.

**Comment by elamaran11** [comment]
@nimakaviani Done. Thanks!

**Comment by nimakaviani** [comment]
great, thanks!

**Review by nimakaviani — APPROVED** [review]
LGTM

**Comment by csantanapr** [comment]
Thank you @elamaran11 for the fix

**Pull request merged**
